using PgbNameCase;

namespace UnitTests.NameCaseFormatterShould;

public class GivenAProgrammersName
{
	[Theory]
	[InlineData("Michael Abrash")]
	[InlineData("Scott Adams")]
	[InlineData("Leonard Adleman")]
	[InlineData("Alfred Aho")]
	[InlineData("J.J. Allaire")]
	[InlineData("Andrei Alexandrescu")]
	[InlineData("Paul Allen")]
	[InlineData("Eric Allman")]
	[InlineData("Marc Andreessen")]
	[InlineData("Bill Atkinson")]
	[InlineData("John Backus")]
	[InlineData("Richard Bartle")]
	[InlineData("Brian Behlendorf")]
	[InlineData("Kent Beck")]
	[InlineData("Donald Becker")]
	[InlineData("Doug Bell")]
	[InlineData("Fabrice Bellard")]
	[InlineData("Tim Berners-Lee")]
	[InlineData("Daniel J. Bernstein")]
	[InlineData("Sabeer Bhatia")]
	[InlineData("Eric Bina")]
	[InlineData("Marc Blank")]
	[InlineData("Joshua Bloch")]
	[InlineData("Grady Booch")]
	[InlineData("Bert Bos")]
	[InlineData("Stephen Richard Bourne")]
	[InlineData("David Bradley")]
	[InlineData("Andrew Braybrook")]
	[InlineData("Lawrence M. Breed")]
	[InlineData("Jack E. Bresenham")]
	[InlineData("Dan Bricklin")]
	[InlineData("Walter Bright")]
	[InlineData("Richard Brodie")]
	[InlineData("Andries Brouwer")]
	[InlineData("Danielle Bunten Berry")]
	[InlineData("Dries Buytaert")]
	[InlineData("Steve Capps")]
	[InlineData("John D. Carmack")]
	[InlineData("Vinton Cerf")]
	[InlineData("Ward Christensen")]
	[InlineData("Edgar F. Codd")]
	[InlineData("Bram Cohen")]
	[InlineData("Alain Colmerauer")]
	[InlineData("Alan Cooper")]
	[InlineData("Alan Cox")]
	[InlineData("Brad Cox")]
	[InlineData("Mike Cowlishaw")]
	[InlineData("Mark Crispin")]
	[InlineData("Ward Cunningham")]
	[InlineData("William Crowther")]
	[InlineData("Dave Cutler")]
	[InlineData("Ole-Johan Dahl")]
	[InlineData("James Duncan Davidson")]
	[InlineData("L. Peter Deutsch")]
	[InlineData("Edsger Dijkstra")]
	[InlineData("Matt Dillon")]
	[InlineData("Jack Dorsey")]
	[InlineData("Martin Dougiamas")]
	[InlineData("Adam Dunkels")]
	[InlineData("Les Earnest")]
	[InlineData("Brendan Eich")]
	[InlineData("Larry Ellison")]
	[InlineData("Marc Ewing")]
	[InlineData("Dan Farmer")]
	[InlineData("Stuart Feldman")]
	[InlineData("David Filo")]
	[InlineData("Brad Fitzpatrick")]
	[InlineData("Andrew Fluegelman")]
	[InlineData("Brian Fox")]
	[InlineData("Martin Fowler")]
	[InlineData("Jim Fruchterman")]
	[InlineData("Elon Gasper")]
	[InlineData("Bill Gates")]
	[InlineData("Steve Gibson")]
	[InlineData("John Gilmore")]
	[InlineData("Adele Goldberg")]
	[InlineData("Ryan C. Gordon")]
	[InlineData("James Gosling")]
	[InlineData("Bill Gosper")]
	[InlineData("Andrew Gower")]
	[InlineData("Paul Gower")]
	[InlineData("Paul Graham")]
	[InlineData("John Graham-Cumming")]
	[InlineData("Ralph Griswold")]
	[InlineData("Richard Greenblatt")]
	[InlineData("Scott Guthrie")]
	[InlineData("Andi Gutmans")]
	[InlineData("Jim Hall")]
	[InlineData("David Heinemeier Hansson")]
	[InlineData("David Albert Huffman")]
	[InlineData("Rebecca Heineman")]
	[InlineData("Anders Hejlsberg")]
	[InlineData("Ted Henter")]
	[InlineData("Andy Hertzfeld")]
	[InlineData("Rich Hickey")]
	[InlineData("D. Richard Hipp")]
	[InlineData("C. A. R. Hoare")]
	[InlineData("James Holmes")]
	[InlineData("Grace Hopper")]
	[InlineData("Dave Hyatt")]
	[InlineData("Miguel de Icaza")]
	[InlineData("Roberto Ierusalimschy")]
	[InlineData("Dan Ingalls")]
	[InlineData("Geir Ivarsøy")]
	[InlineData("Kenneth E. Iverson")]
	[InlineData("Toru Iwatani")]
	[InlineData("Bo Jangeborg")]
	[InlineData("Paul Jardetzky")]
	[InlineData("Lynne Jolitz")]
	[InlineData("William Jolitz")]
	[InlineData("Stephen C. Johnson")]
	[InlineData("Bill Joy")]
	[InlineData("Robert K. Jung")]
	[InlineData("Poul-Henning Kamp")]
	[InlineData("Mitch Kapor")]
	[InlineData("Phil Katz")]
	[InlineData("Alan Kay")]
	[InlineData("Mel Kaye")]
	[InlineData("John George Kemeny")]
	[InlineData("Stan Kelly-Bootle")]
	[InlineData("Brian Kernighan")]
	[InlineData("Gary Kildall")]
	[InlineData("Tom Knight")]
	[InlineData("Jim Knopf")]
	[InlineData("Donald E. Knuth")]
	[InlineData("Andrew Koenig")]
	// [InlineData("Andre LaMothe")] Combined La names are an issue *
	[InlineData("Tom Lane")]
	[InlineData("Leslie Lamport")]
	[InlineData("Butler Lampson")]
	[InlineData("Sam Lantinga")]
	[InlineData("Richard H. Lathwell")]
	[InlineData("Chris Lattner")]
	[InlineData("Samuel J Leffler")]
	[InlineData("Rasmus Lerdorf")]
	[InlineData("Michael Lesk")]
	[InlineData("Gordon Letwin")]
	[InlineData("Rockford Lhotka")]
	[InlineData("Håkon Wium Lie")]
	[InlineData("Robert Love")]
	[InlineData("Ada Lovelace")]
	// [InlineData("Al Lowe")] Al is an issue *
	[InlineData("Raphael Manfredi")]
	[InlineData("Khaled Mardam-Bey")]
	[InlineData("Yukihiro Matsumoto")]
	[InlineData("John McCarthy")]
	[InlineData("Craig McClanahan")]
	[InlineData("Daniel D. McCracken")]
	[InlineData("Douglas McIlroy")]
	[InlineData("Shawn McKenzie")]
	[InlineData("Marshall Kirk McKusick")]
	[InlineData("Bertrand Meyer")]
	[InlineData("Scott Meyers")]
	[InlineData("Bob Miner")]
	[InlineData("Jeff Minter")]
	[InlineData("Lou Montulli")]
	[InlineData("Bram Moolenaar")]
	[InlineData("David Moon")]
	[InlineData("Charles H. Moore")]
	[InlineData("Roger Moore")]
	[InlineData("Mike Muuss")]
	[InlineData("Patrick Naughton")]
	[InlineData("Peter Naur")]
	[InlineData("Fredrik Neij")]
	[InlineData("Graham Nelson")]
	[InlineData("Peter Norton")]
	[InlineData("Kristen Nygaard")]
	// [InlineData("Ed Oates")] , Ed is an issue *
	[InlineData("Martin Odersky")]
	[InlineData("Jarkko Oikarinen")]
	[InlineData("Oliver Twins")]
	[InlineData("John Ousterhout")]
	[InlineData("Onel de Guzman")]
	[InlineData("Larry Page")]
	[InlineData("Alexey Pajitnov")]
	[InlineData("Seymour Papert")]
	[InlineData("Tim Paterson")]
	[InlineData("Markus Persson")]
	[InlineData("Jeffrey Peterson")]
	[InlineData("Charles Petzold")]
	[InlineData("Rob Pike")]
	[InlineData("Kent Pitman")]
	[InlineData("Theo de Raadt")]
	[InlineData("Jef Raskin")]
	[InlineData("Eric S. Raymond")]
	[InlineData("Hans Reiser")]
	[InlineData("John Resig")]
	[InlineData("Craig Reynolds")]
	[InlineData("Dennis Ritchie")]
	[InlineData("Ron Rivest")]
	[InlineData("John Romero")]
	[InlineData("Blake Ross")]
	[InlineData("Guido van Rossum")]
	[InlineData("Jeff Rulifson")]
	[InlineData("Rusty Russell")]
	[InlineData("Steve Russell")]
	[InlineData("Mark Russinovich")]
	[InlineData("Bob Sabiston")]
	[InlineData("Muni Sakya")]
	[InlineData("Carl Sassenrath")]
	[InlineData("Chris Sawyer")]
	[InlineData("Bill Schelter")]
	[InlineData("Randal L. Schwartz")]
	[InlineData("Adi Shamir")]
	[InlineData("Mike Shaver")]
	[InlineData("Cliff Shaw")]
	[InlineData("Zed Shaw")]
	[InlineData("Emily Short")]
	[InlineData("Jacek Sieka")]
	[InlineData("Ken Silverman")]
	[InlineData("Charles Simonyi")]
	[InlineData("Colin Simpson")]
	[InlineData("Rich Skrenta")]
	[InlineData("Matthew Smith")]
	[InlineData("Henry Spencer")]
	[InlineData("Joel Spolsky")]
	[InlineData("Quentin Stafford-Fraser")]
	[InlineData("Richard Stallman")]
	[InlineData("Guy Steele")]
	[InlineData("Alexander Stepanov")]
	[InlineData("Ludvig Strigeus")]
	[InlineData("Bjarne Stroustrup")]
	[InlineData("Zeev Suraski")]
	[InlineData("Gerald Jay Sussman")]
	[InlineData("Herb Sutter")]
	[InlineData("Gottfrid Svartholm")]
	[InlineData("Tim Sweeney")]
	[InlineData("Andrew S. Tanenbaum")]
	[InlineData("Audrey Tang")]
	[InlineData("Simon Tatham")]
	[InlineData("Larry Tesler")]
	[InlineData("Jon Stephenson von Tetzchner")]
	[InlineData("Avie Tevanian")]
	[InlineData("Ken Thompson")]
	[InlineData("Michael Tiemann")]
	[InlineData("Linus Torvalds")]
	[InlineData("Andrew Tridgell")]
	[InlineData("Roy Trubshaw")]
	[InlineData("Bob Truel")]
	[InlineData("Wietse Venema")]
	[InlineData("Pat Villani")]
	[InlineData("Paul Vixie")]
	[InlineData("Patrick Volkerding")]
	[InlineData("Larry Wall")]
	[InlineData("Bob Wallace")]
	[InlineData("John Walker")]
	[InlineData("John Warnock")]
	[InlineData("Joseph Weizenbaum")]
	[InlineData("Robert Watson")]
	[InlineData("Pei-Yuan Wei")]
	[InlineData("Peter J. Weinberger")]
	[InlineData("Andrew Welch")]
	[InlineData("David Wheeler")]
	[InlineData("Arthur Whitney")]
	[InlineData("Bruce Wilcox")]
	[InlineData("Evan Williams")]
	[InlineData("Roberta Williams")]
	[InlineData("Sophie Wilson")]
	[InlineData("Dave Winer")]
	[InlineData("Niklaus Wirth")]
	[InlineData("Stephen Wolfram")]
	[InlineData("Don Woods")]
	[InlineData("Steve Wozniak")]
	[InlineData("Will Wright")]
	[InlineData("Jerry Yang")]
	[InlineData("Victor Yngve")]
	[InlineData("Jamie Zawinski")]
	[InlineData("Philip Zimmermann")]
	[InlineData("Mark Zuckerberg")]
	[InlineData("BJ Golden")]
	public void CorrectlyFormatAName(string expectedName)
	{
		var nameToBeFormatted = expectedName.ToLower();

		var actualName = NameCaseFormatter.Format(nameToBeFormatted);

		Assert.Equal(expectedName, actualName);
	}
}
